### ISSUE TITLE
Illegal string offset 'display'

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/textformatter#8] opened 2023-03-31 15:46 UTC
`Warning: Illegal string offset 'display' in textformatter_field_formatter_view() (line 284 of /app/modules/contrib/textformatter/textformatter.module).`

This warning appears on node pages with taxonomy links set to display as links.  This is in a site ported from D7.  In D7 there's an option to add an HTML wrapper around the list, which isn't available in Backdrop. 

The taxonomy terms on the page display incorrectly as well as just an opening bracket `<` instead of the actual term, so it seems like it might not be handling the HTML wrapper.  Switching to the Label option for textformatter works, but is a more limited display.

**Comment by herbdool** [comment] 2024-11-13 20:52
I see the same error. This also happens with entityreference fields.

In `textformatter_contrib_entityreference_field_create_list()` it returns a list of items which are just strings, but `textformatter_field_formatter_view()` expects each list item to be an array of name and display.

**Comment by herbdool** [comment] 2024-11-13 20:53
@laryn can you take a look at this? Not sure if the module is working for others or not, but definitely getting a fatal error.

**Comment by laryn** [comment] 2024-11-13 21:19
@herbdool I just spun up a demo site, installed the module, and used it to display Tags as a linked list:
![CleanShot 2024-11-13 at 15 18 57@2x](https://github.com/user-attachments/assets/06eb10bf-93df-4770-8d6f-779b3dcc7d27)

Is yours a D7 upgrade, too?

**Comment by laryn** [comment] 2024-11-13 21:27
I'll try an Entityreference field.

EDIT: @herbdool How do I even do this with an Entityreference field? 😅 

EDIT2: Got it. Yes, the contrib submodule does appear to need some work. Honestly I don't know that I've ever used it before. I'll see if it's a quick fix.

**Comment by laryn** [comment] 2024-11-13 22:15
@herbdool and @pgrayove-mcpl -- it's been a while since I worked on this module but from what I can tell it had a poorly implemented attempt to allow sorting that only really worked on Taxonomy Terms. Could you test the PR linked here to see if it helps in your case?

**Comment by herbdool** [comment] 2024-11-13 22:33
@laryn I've tested and it appears to work. No fatal error and the field is a list. I haven't tested sorting.

By the way, can you update the checkbox text on the field settings for entity reference? It says:

> Link list items to their node entity.
> Generate item list with links to the node page

and should be more generic since it could be any kind of entity.

**Comment by laryn** [comment] 2024-11-13 22:49
@herbdool Suggestions welcome, but here's a first attempt: 
https://github.com/backdrop-contrib/textformatter/pull/10/commits/c72b098688095120a6df1fc3acd4b79f66421299

**Comment by herbdool** [comment] 2024-11-13 22:56
@laryn looks good.

**Comment by laryn** [comment] 2024-11-13 23:23
Thanks @herbdool!

@pgrayove-mcpl I've merged and closed this for now -- I don't think I was able to replicate your issue. If you're still having an issue with the latest code, please feel free to reopen and we can try to find steps to reproduce and then fix it.

**Comment by pgrayove-mcpl** [comment] 2024-11-14 14:42
@laryn Maybe there's something else going on, but I am not seeing the fix on my site.  I installed the module and set up a couple of different taxonomy vocabularies to display as lists.  You can see the comma separated list for blogs and then the unordered HTML list for blog topics.
![image](https://github.com/user-attachments/assets/1215b273-51f7-4f6f-b6bc-9f464ceb9522)

Here's how blog and blog topics are displaying on a post.
![image](https://github.com/user-attachments/assets/682f385c-1924-43a6-b2da-346516ce1f52)

I'm still getting this error message as well.
`Warning: Illegal string offset 'display' in textformatter_field_formatter_view() (line 284 of /app/modules/contrib/textformatter/textformatter.module).`

**Comment by laryn** [comment] 2024-11-14 14:53
Thanks @pgrayove-mcpl — can you confirm you’re using the latest code as well? (Not necessarily the latest release)

**Comment by pgrayove-mcpl** [comment] 2024-11-14 14:59
@laryn I'm using the 1.x-1.4.1 version and I didn't have it previously installed on my test site so it shouldn't be trying to use any older code.

**Comment by laryn** [comment] 2024-11-14 15:04
@pgrayove-mcpl I haven't made a new release yet with the recent changes -- can you either pull from Github or download the Zip as shown here and let me know if you still see the same?
![CleanShot 2024-11-14 at 09 03 33@2x](https://github.com/user-attachments/assets/02976f9f-114c-425d-91c5-0f82b38b557f)

**Comment by pgrayove-mcpl** [comment] 2024-11-14 15:13
Ah, sorry, @laryn, I hadn't realized the difference.  Just tested and, yes, it is working as expected!!
![image](https://github.com/user-attachments/assets/40cabe5e-8b8a-4400-bca6-90698151f021)

**Comment by laryn** [comment] 2024-11-14 15:15
@pgrayove-mcpl No problem at all -- thanks for testing and confirming, much appreciated!

**Closed as completed** 2024-11-14 15:16 UTC

**Comment by pgrayove-mcpl** [comment] 2024-11-14 15:17
I'm excited to start using this module again. Thanks @laryn and @herbdool for your work on this!

**Comment by laryn** [comment] 2024-11-14 15:27
I'll flag you on the other open issue when I have something to test there related to upgrades, if you're willing. Once that's in I'll make a new release.
